### Find all content
GET http://localhost:8080/api/content

### Get content by id
GET http://localhost:8080/api/content/1

### Create new Content
POST http://localhost:8080/api/content
Content-Type: application/json

{
  "title": "Test",
  "desc": "My second Blog Post",
  "Status": "IDEA",
  "ContentType": "ARTICLE",
  "timeCreated": "2026-08-17T19:15:30.313512",
  "timeUpdated": null,
  "url": ""
}

### Update existing content
PUT http://localhost:8080/api/content/1
Content-Type: application/json

{
  "id": 1,
  "title": "My first Blog Post",
  "desc": "My first Blog Post",
  "Status": "IDEA",
  "ContentType": "ARTICLE",
  "timeCreated": "2026-08-17T19:15:30.313512",
  "timeUpdated": "2026-08-17T19:15:30.313512",
  "url": ""
}

### Delete existing content
DELETE http://localhost:8080/api/content/1